% stationmap.m
% Todd Anderson
% October 31 2022
%
% Plot stations from stations.dat

stations = importdata("stations.mat");
load coastlines;

stationlist = ["Fairbanks"; ...
               "Sodankyla"; ...
               "Yakutsk"; ...
               "Edmonton"; ...
               "Sheffield"; ...
               "Gasu"; ...
               "MSSL"; ...
               "Paris"; ...
               "Seattle"; ...
               "StJohns"; ...
               "MTU"; ...
               "Tihany"; ...
               "Transylvania"; ...
               "Rochester"; ...
               "Monmouth"; ...
               "Boulder"; ...
               "LANL"];

carllist = ["Dunedin"; ...   
            "Perth"; ...     
            "Brisbane"; ...  
            "Suva"; ...      
            "Seattle"; ...   
            "Tahiti"; ...    
            "Lisbon"; ...
            "Hermanus"; ...  
            "Peru"; ...      
            "Davis"; ...     
            "Cordoba"; ...   
            "Pune"; ...      
            "Maido"; ...     
            "Monmouth"; ...  
            "Yerevan"; ...   
            "Honolulu"; ...  
            "Rothera"; ...   
            "Ascension"; ... 
            "Boulder"; ...   
            "UCLA"; ...      
            "Yakutsk"; ...   
            "ScottBase"; ... 
            "SANAEBase"; ... 
            "Fairbanks"; ... 
            "Chofu"; ...     
            "MTU"; ...       
            "Edmonton"; ...  
            "MarionIsland"; ...
            "Valparaiso"; ...
            "Valencia"; ...
            "Sheffield"; ...
            "BuenosAires"; ...
            "Bayamon"; ...   
            "Chile"; ...     
            "StJohns"; ...
            "Transylvania"; ...
            "FUTA"; ...
            "Doon"; ...      
            "Milesovka"; ... 
            %"Quito"; ...
            "LaPaz"; ...     
            "Gasu"; ...
            "ScottBaseEz"; ...
            "USM"; ...
            "Kazakhstan"; ...
            "Paris"; ...     
            "Belem"; ...     
            "Bend"; ...
            "MIT"; ...       
            "Bryansk"; ...   
            "Kingston"; ...  
            "Dakar"];

lat = zeros(size(stationlist));
lon = zeros(size(stationlist));

for i = 1:length(stationlist)
    station_ind = find(strcmp([stations{:,3}],stationlist(i)));

    lat(i) = stations{station_ind,1};
    lon(i) = stations{station_ind,2};
    
end

clat = zeros(size(carllist));
clon = zeros(size(carllist));

for j = 1:length(carllist)
    station_ind = find(strcmp([stations{:,3}],carllist(j)));

    clat(j) = stations{station_ind,1};
    clon(j) = stations{station_ind,2};
end

figure(1)
hold off
worldmap("World");
geoshow(coastlat, coastlon, "Color", "black");
hold on
geoshow([stations{:,1}], [stations{:,2}], "DisplayType", "multipoint", "Marker", "square", "MarkerFaceColor", "red");
geoshow(clat, clon, "DisplayType","multipoint", "Marker","^","MarkerFaceColor","yellow", "MarkerEdgeColor", "black");
geoshow(lat, lon, "DisplayType","multipoint", "Marker","^","MarkerFaceColor","green");

for k = 1:length(clat)
    textm(clat(k)+1, clon(k)-1, [carllist{k}]);
end