% stationmap.m
% Todd Anderson
% October 31 2022
%
% Plot stations from stations.dat

stations = importdata("stations.mat");
load coastlines;

% stationlist = ["Fairbanks"; ...
%                "Sodankyla"; ...
%                "Yakutsk"; ...
%                "Edmonton"; ...
%                "Sheffield"; ...
%                "Gasu"; ...
%                "MSSL"; ...
%                "Paris"; ...
%                "Seattle"; ...
%                "StJohns"; ...
%                "MTU"; ...
%                "Tihany"; ...
%                "Transylvania"; ...
%                "Rochester"; ...
%                "Monmouth"; ...
%                "Boulder"; ...
%                "LANL"];

stationlist = ["Anchorage";
              "Ascension";
              "Bayamon";
              "Bend";
              "Boulder";
              "Bryansk";
              "BuenosAires";
              "Chile";
              "Chofu";
              "Cordoba";
              "Dakar";
              "Dunedin";
              "Edmonton";
              "Fairbanks";
              "FUTA";
              "Gasu";
              "Hermanus";
              "Honolulu";
              "Kazakhstan";
              "Kingston";
              "LANL";
              "LaPaz";
              "Lisbon";
              "MarionIsland";
              "Milesovka";
              "Monmouth";
              "MSSL";
              "MTU";
              "Paris";
              "Perth";
              "Peru";
              %"Quito";
              "Rikitea";
              "Rochester";
              "Rothera";
              "SANAEBase";
              "ScottBase";
              "ScottBaseEz";
              "Seattle";
              "Sheffield";
              "Sodankyla";
              "StJohns";
              "TelAviv";
              "Tihany";
              "Transylvania";
              "Trelew";
              "USM";
              "Valencia";
              "Valparaiso";
              "Yakutsk";
              "Yerevan"];

% carllist = ["Dunedin"; ...   
%             "Perth"; ...     
%             "Brisbane"; ...  
%             "Suva"; ...      
%             "Seattle"; ...   
%             "Tahiti"; ...    
%             "Lisbon"; ...
%             "Hermanus"; ...  
%             "Peru"; ...      
%             "Davis"; ...     
%             "Cordoba"; ...   
%             "Pune"; ...      
%             "Maido"; ...     
%             "Monmouth"; ...  
%             "Yerevan"; ...   
%             "Honolulu"; ...  
%             "Rothera"; ...   
%             "Ascension"; ... 
%             "Boulder"; ...   
%             "UCLA"; ...      
%             "Yakutsk"; ...   
%             "ScottBase"; ... 
%             "SANAEBase"; ... 
%             "Fairbanks"; ... 
%             "Chofu"; ...     
%             "MTU"; ...       
%             "Edmonton"; ...  
%             "MarionIsland"; ...
%             "Valparaiso"; ...
%             "Valencia"; ...
%             "Sheffield"; ...
%             "BuenosAires"; ...
%             "Bayamon"; ...   
%             "Chile"; ...     
%             "StJohns"; ...
%             "Transylvania"; ...
%             "FUTA"; ...
%             "Doon"; ...      
%             "Milesovka"; ... 
%             %"Quito"; ...
%             "LaPaz"; ...     
%             "Gasu"; ...
%             "ScottBaseEz"; ...
%             "USM"; ...
%             "Kazakhstan"; ...
%             "Paris"; ...     
%             "Belem"; ...     
%             "Bend"; ...
%             "MIT"; ...       
%             "Bryansk"; ...   
%             "Kingston"; ...  
%             "Dakar";
%             "LANL"];

lat = zeros(size(stationlist));
lon = zeros(size(stationlist));

for i = 1:length(stationlist)
    station_ind = find(strcmp([stations{:,3}],stationlist(i)));

    lat(i) = stations{station_ind,1};
    lon(i) = stations{station_ind,2};
    
end

% generate table of stations; nice for copy and pasting text if needed
sferic_stations = table(stationlist, lat, lon);

% clat = zeros(size(carllist));
% clon = zeros(size(carllist));
% 
% for j = 1:length(carllist)
%     station_ind = find(strcmp([stations{:,3}],carllist(j)));
% 
%     clat(j) = stations{station_ind,1};
%     clon(j) = stations{station_ind,2};
% end

%%
figure(1)
hold off
worldmap("World");
geoshow(coastlat, coastlon, "Color", "black");
hold on
geoshow([stations{:,1}], [stations{:,2}], "DisplayType", "multipoint", "Marker", "square", "MarkerFaceColor", "blue", "MarkerEdgeColor","black", "MarkerSize", 8);
% geoshow(clat, clon, "DisplayType","multipoint", "Marker","^","MarkerFaceColor","yellow", "MarkerEdgeColor", "black");
geoshow(lat, lon, "DisplayType","multipoint", "Marker","^","MarkerFaceColor","green", "MarkerEdgeColor","black", "MarkerSize", 10);

t = title("WWLLN stations");
t.FontSize = 15;
l = legend(["","","sferics unavailable (78)","sferics available (50)"]);
l.Location = "southoutside";
l.FontSize = 15;
% for k = 1:length(lat)
%     textm(lat(k)+1, lon(k)-1, [stationlist{k}]);
% end