% pathGrid_10m.m
% 17 December 2018
%
% Takes 10-minute stroke-station pair files as input and calculates
% whole-day matrix of grid crossings by stroke-station paths.  Clears
% grid_cell before loading next 10-minute file to reduce memory usage.
%
% INPUTS:
%       strokelist_lite_10m_*.mat
%           File of stroke-station pairs generated by getPathsFromAP.m from
%           APfiles.  10-minute version has name format
%           strokelist_lite_10m_yyyymmddHHMM.mat.
%
% FUNCTIONS:
%       pg_gridcell.m
%           Converts strokelist to 180 x 360 cell array 'grid_cell'.  These
%           outputs are large (total 1-day = several GB), so each grid_cell
%           is cleared before proceding to next 10-minute strokelist.
%
%       pg_gridcross.m
%           Converts grid_cell to grid_crossings, a 180 x 360 matrix.  Each
%           element is the length of the corresponding cell in grid_cell.
%
% OUTPUTS:
%       grid_crossings_all*.mat
%           180 x 360 x 144 matrix of grid_crossings.  Each of 144 frames
%           represents stroke-station path crossings during the 10-minute
%           window in each strokelist file.
%
%% Input parameters:

% Enter start and stop APfile dates (inclusive).
starttime = datenum(2019,03,20,00,00,00);
stoptime = datenum(2019,03,21,00,00,00);

% Enter number of time bins (e.g. 144 10-minute time bins per day)
frames = 144;

minute_bin_edges = linspace(starttime,stoptime,frames+1);

grid_crossings = zeros(180,360,frames);

for m = 1:frames
    
    filestr = datestr(minute_bin_edges(m),'yyyymmddHHMM');
    filenum = str2double(filestr);
    strokefile = sprintf('strokelist_lite_10m_%d.mat',filenum);
    
    gridcell = pg_gridcell(strokefile);more
    
    gridcross = pg_gridcross(gridcell);
    
    grid_crossings(:,:,m) = gridcross;
    
    % append to log file
    msg = sprintf('Completed run %s',filestr);
    fid = fopen('pgLog.txt', 'a');
    if fid == -1
        error('Cannot open log file.');
    end
    fprintf(fid, '%s: %s\n', datestr(now, 0), msg);
    fclose(fid);
    
end

save('grid_crossings_10m_20190320.mat','grid_crossings');
